### ISSUE TITLE
email validation 

### ISSUE THREAD

**Issue by mopi1402** [sonicwong/ionic-input-clearable#1]
The button is not showing until the email is correct :

`<input ionic-input-clearable name="email" ng-model="form.email" type="email" placeholder="email" required>`

fix :
`$scope.isInputFieldEmpty = function () {
                return ($element[0].value == '' || $element[0].value == null );
                //return ($scope.ngModel == '' || $scope.ngModel == null );
}`

**Comment by sonicwong** [comment]
Updated @ v1.0.1
