### ISSUE TITLE
[feature] show button only during editing

### ISSUE THREAD

**Issue by mopi1402** [sonicwong/ionic-input-clearable#2]
The cross will be available only when the input has the focus (like in ios) :

```
   var element = $element[0];

   $element.bind( 'focus', function() {
         $scope.$digest();
   });

   $element.bind( 'blur', function() {
         $scope.$digest();
   });

   $scope.isInputFieldEmpty = function () {
      return (document.activeElement !== element || element.value == '' || element.value == null );
   }
```

**Comment by sonicwong** [comment]
Hi mopi1402,

I know cross will show same as your idea in ionic v2:
http://ionicframework.com/docs/v2/api/components/input/Input/

But I prefer to keep same as jquery mobile personally:
http://demos.jquerymobile.com/1.4.5/forms-gallery/

I will add an option to select which logic to use in next build.

**Comment by sonicwong** [comment]
Updated @ v1.0.1

**Comment by mopi1402** [comment]
Thanks for the update :)
