### ISSUE TITLE
prevent the blur when clicking on the clear button

### ISSUE THREAD

**Issue by mopi1402** [sonicwong/ionic-input-clearable#6]
Feel free to add this one to your directive in order to prevent the input to blur when the user click on the clear button :

$scope.clearInputField = function ( event ) {
                    $scope.ngModel = '';

```
                function preventBluring() {
                    element.focus();
                    $element.unbind( 'blur', preventBluring );
                }

                //keep focus on the field when click on the clear button
                $element.bind( 'blur' , preventBluring );
            };
```

**Comment by sonicwong** [comment]
Would you upload a complete file or submit a merge request?
